### ISSUE TITLE
Handling SSL certificates in firefox browser using protractor tool

### ISSUE THREAD

**Issue by shalinirakesh** [DanTup/TestAdapters#38]
I am getting 'connection is not secure' error while accessing a website.
How can i handle the SSL certificate page in protractor 
![not secure error in firefox](https://user-images.githubusercontent.com/25221923/28772876-25f92b6a-7605-11e7-895e-796b1bd6c7be.PNG)

**Comment by DanTup** [comment]
I'm afraid this appears unrelated to this extension and I wouldn't know how to debug. My guess is that either there's something wrong with the site or you have a proxy in the middle issuing its own SSL certificate which Firefox doesn't like. There may be a way you can tell Firefox to trust it (I think FF has its own certificate store?), but I don't use it so probably wouldn't be the best person to try and troubleshoot!

**Comment by shalinirakesh** [comment]
I was able to handle the SSL certificate page by making the below changes in conf.js

     seleniumAddress: 'http://localhost:4444/wd/hub',
     directConnect: false,
                
  // Capabilities to be passed to the webdriver instance.
     capabilities: {
     'browserName': 'firefox',
      marionette: true,
      acceptInsecureCerts : true 
     
  },
  I have also run the webdriver-manager start from command prompt
